# Generated by Django 5.2.8 on 2025-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_delivery_address_alter_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='', help_text='Adresa dostave je obavezna'),
        ),
    ]
