# Generated by Django 5.2.8 on 2025-11-27 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Unesite ispravan broj telefona (npr: 0641234567 ili +381641234567)', regex='^(\\+381|0)[0-9]{8,9}$')])),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontakt poruka',
                'verbose_name_plural': 'Kontakt poruke',
                'ordering': ['-created_at'],
            },
        ),
    ]
