# Generated by Django 5.2.8 on 2025-11-27 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Unesite ispravan broj telefona (npr: 0641234567 ili +381641234567)', regex='^(\\+381|0)[0-9]{8,9}$')]),
        ),
    ]
